### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kithack** [kit-tm/PTP#2]
GPLv3?

**Comment by marfl** [comment]
I guess so. Is it enough to add a license.txt to the project and mention the license in the README?

**Comment by kithack** [comment]
https://www.gnu.org/licenses/gpl-faq.html

You should put a notice at the start of each source file, stating what license it carries, in order to avoid risk of the code's getting disconnected from its license. If your repository's README says that source file is under the GNU GPL, what happens if someone copies that file to another program? That other context may not show what the file's license is. It may appear to have some other license, or no license at all (which would make the code nonfree).

Adding a copyright notice and a license notice at the start of each source file is easy and makes such confusion unlikely.

This has nothing to do with the specifics of the GNU GPL. It is true for any free license.

**Comment by kithack** [comment]
Otherwise it says:
This statement should be in each source file. A clear statement in the program's README file is legally sufficient as long as that accompanies the code, but it is easy for them to get separated. Why take a risk of uncertainty about your code's license?

**Comment by kithack** [comment]
The preamble and instructions are integral parts of the GNU GPL and may not be omitted. In fact, the GPL is copyrighted, and its license permits only verbatim copying of the entire GPL. (You can use the legal terms to make another license but it won't be the GNU GPL.)

**Comment by kithack** [comment]
PTP uses GPL-3.0.
LICENSE.txt file has been added and linked from the README.
